name: ezbids
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - nibabel
  - pandas
  - matplotlib
  - pyyaml
  - pydicom
  - natsort
  - pillow
  - mne
  - mne-bids
  - pip
  - pip:
    - pydeface
    - quickshear
    - pypet2bids
