#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 1 11:45:04 2021

determine PED

@author: dlevitas
"""

import json
import nibabel as nib

def correctPE(pe_direction, ornt):
    '''
    Takes pe_direction and image orientation to correct pe_direction 
    if need be. Correction occurs if the pe_direction is "xyz". Otherwise,
    no correction is necessary

    Parameters
    ----------
    pe_direction : string
        Value from PhaseEncodingDirection in json file generated by dcm2niix
    ornt: string
        Value of ''.join(nib.aff2axcodes(nii_img.affine))

    Returns
    -------
    proper_pe_direction: string
        Either input pe_direction (if ijk), or corrected pe_direction (if xyz)
    '''
    
    axes = (("R", "L"), ("A", "P"), ("S", "I"))
    proper_ax_idcs = {"i": 0, "j": 1, "k": 2}

    # pe_direction is ijk (no correction necessary)
    if any(x in pe_direction for x in ['i','i-','j','j-','k','k']):
        proper_pe_direction = pe_direction
        
    # pe_direction xyz (correction required)
    else:
        
        improper_ax_idcs = {"x": 0, "y": 1, "z": 2}
        axcode = ornt[improper_ax_idcs[pe_direction[0]]]
        axcode_index = improper_ax_idcs[pe_direction[0]]
        inv = pe_direction[1:] == "-"
        
        if pe_direction[0] == 'x':
            if 'L' in axcode:
                inv = not inv
        elif pe_direction[0] == 'y':
            if 'P' in axcode:
                inv = not inv
        elif pe_direction[0] == 'z':
            if 'I' in axcode:
                inv = not inv
        else:
            ValueError('pe_direction does not contain letter i, j, k, x, y, or z')
        
        if inv:
            polarity = '-'
        else:
            polarity = ''
            
        proper_pe_direction = [key for key, value in proper_ax_idcs.items() if value == axcode_index][0] + polarity     
        
    return proper_pe_direction



def determineDir(pe_direction, ornt):
    '''
    Takes pe_direction and image orientation to determine direction 
    required by BIDS "_dir-" label

    Parameters
    ----------
    pe_direction : string
        Value from PhaseEncodingDirection in json file generated by dcm2niix
    ornt: string
        Value of ''.join(nib.aff2axcodes(nii_img.affine))

    Returns
    -------
    dir: string
        direction for BIDS "_dir-" label
    '''
    
    axes = (("R", "L"), ("A", "P"), ("S", "I"))
    ax_idcs = {"i": 0, "j": 1, "k": 2}
    axcode = ornt[ax_idcs[pe_direction[0]]]
    inv = pe_direction[1:] == "-"
    
    if pe_direction[0] == 'i':
        if 'L' in axcode:
            inv = not inv
    elif pe_direction[0] == 'j':
        if 'P' in axcode:
            inv = not inv
    elif pe_direction[0] == 'k':
        if 'I' in axcode:
            inv = not inv
        
    for ax in axes:
        for flip in (ax, ax[::-1]):
            if flip[not inv].startswith(axcode):
                direction = "".join(flip)
                    
    return direction
        
# Perform check
test = ('y-', 'LAS')
proper_pe_direction = correctPE(test[0], test[1])
direction = determineDir(proper_pe_direction, test[1])

print("With a pe_direction of '{}' and orientation of '{}', the " \
    "proper pe_direction is '{}' " \
    "and the PED value is '{}'".format(test[0], test[1], proper_pe_direction, direction))
