// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
    export interface GlobalComponents {
        AnalysisErrors: (typeof import('./src/components/analysisErrors.vue'))['default'];
        AsyncImageLink: (typeof import('./src/components/AsyncImageLink.vue'))['default'];
        Columnselecter: (typeof import('./src/components/columnselecter.vue'))['default'];
        Datatype: (typeof import('./src/components/datatype.vue'))['default'];
        ElAffix: (typeof import('element-plus/es'))['ElAffix'];
        ElAlert: (typeof import('element-plus/es'))['ElAlert'];
        ElAutocomplete: (typeof import('element-plus/es'))['ElAutocomplete'];
        ElBadge: (typeof import('element-plus/es'))['ElBadge'];
        ElButton: (typeof import('element-plus/es'))['ElButton'];
        ElCard: (typeof import('element-plus/es'))['ElCard'];
        ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox'];
        ElCol: (typeof import('element-plus/es'))['ElCol'];
        ElCollapse: (typeof import('element-plus/es'))['ElCollapse'];
        ElCollapseItem: (typeof import('element-plus/es'))['ElCollapseItem'];
        ElContainer: (typeof import('element-plus/es'))['ElContainer'];
        ElDialog: (typeof import('element-plus/es'))['ElDialog'];
        ElDropdown: (typeof import('element-plus/es'))['ElDropdown'];
        ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem'];
        ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu'];
        ElFooter: (typeof import('element-plus/es'))['ElFooter'];
        ElForm: (typeof import('element-plus/es'))['ElForm'];
        ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
        ElHeader: (typeof import('element-plus/es'))['ElHeader'];
        ElIcon: (typeof import('element-plus/es'))['ElIcon'];
        ElInput: (typeof import('element-plus/es'))['ElInput'];
        ElLink: (typeof import('element-plus/es'))['ElLink'];
        ElMain: (typeof import('element-plus/es'))['ElMain'];
        ElMenu: (typeof import('element-plus/es'))['ElMenu'];
        ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
        ElOption: (typeof import('element-plus/es'))['ElOption'];
        ElOptionGroup: (typeof import('element-plus/es'))['ElOptionGroup'];
        ElPopover: (typeof import('element-plus/es'))['ElPopover'];
        ElProgress: (typeof import('element-plus/es'))['ElProgress'];
        ElRadio: (typeof import('element-plus/es'))['ElRadio'];
        ElRow: (typeof import('element-plus/es'))['ElRow'];
        ElSelect: (typeof import('element-plus/es'))['ElSelect'];
        ElStep: (typeof import('element-plus/es'))['ElStep'];
        ElSteps: (typeof import('element-plus/es'))['ElSteps'];
        ElTable: (typeof import('element-plus/es'))['ElTable'];
        ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn'];
        ElTag: (typeof import('element-plus/es'))['ElTag'];
        ElTooltip: (typeof import('element-plus/es'))['ElTooltip'];
        Loading: (typeof import('element-plus/es'))['ElLoadingDirective'];
        ManageUsersDialog: (typeof import('./src/components/dialogs/ManageUsersDialog.vue'))['default'];
        ModalityForm: (typeof import('./src/components/modalityForm.vue'))['default'];
        Niivue: (typeof import('./src/components/niivue.vue'))['default'];
        Showfile: (typeof import('./src/components/showfile.vue'))['default'];
    }
}

export {};
