Bootstrap: docker
From: node:16
Stage: spython-base

%files
    . /ui

%post
    mkdir -p /ui
    cd /ui
    npm install
    # Hacky solution for dealing with path issue
    cp singularity_vite node_modules/.bin/vite
    exec npm run dev "$@"

%runscript
    cd /ui
    # exec /bin/bash npm run dev "$@"
    exec npm run dev "$@"
    # exec npm run dev

%startscript
    cd /ui
    # exec /bin/bash npm run dev "$@"
    exec npm run dev "$@"
    # npm run dev
